version: "3.9"

services:
  fake_news_prediction:
    build:
      context: .
      dockerfile: 02_deployment/Dockerfile
    image: fake-news-prediction-service:v1
    ports:
      - "5000:5000"
      - "9696:9696"
    volumes:
      - ~/.aws:/root/.aws:ro
    environment:
      - AWS_DEFAULT_REGION=eu-west-1
      - MLFLOW_TRACKING_URI=https://fictional-adventure-wr9prgq477xwfgggp.github.dev/:5000
    restart: always
    entrypoint: ["gunicorn", "--bind=0.0.0.0:9696", "predict:app"]