[tool.pylint.messages_control]

disable = [
    "line-too-long",
    "broad-exception-caught",
    "bare-except",
    "too-many-arguments",
    "too-many-positional-arguments",
    "too-many-locals",
    "wrong-import-position"
]

[tool.black]
line-length = 88
target-version = ['py312']
skip-string-normalization = true

[tool.isort]
multi_line_output = 3
length_sort = true