[tool.pylint.messages_control]

disable = [
    "line-too-long",
    "broad-exception-caught",
    "bare-except",
    "too-many-arguments",
    "too-many-positional-arguments",
    "too-many-locals"
]