name: CI-Tests
on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'

env:
  AWS_DEFAULT_REGION: 'eu-west-1'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12.2
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.2

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Download SpaCy model
        run: pipenv run python -m spacy download en_core_web_sm

      - name: Run Unit tests
        run: pipenv run pytest tests/

      - name: Lint
        run: pipenv run pylint --recursive=y .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Start server
        run: |
          gunicorn --bind 0.0.0.0:9696 predict:app &
          sleep 5

      - name: Make integration test script executable
        run: chmod +x integration_test/run.sh

      - name: Integration Test
        working-directory: 'integration_test'
        run: |
          . run.sh
